### ISSUE TITLE
fail_missing_attributes invoked in simple mode

### ISSUE THREAD

**Issue by kirillplatonov** [mrbrdo/datasource#1]
```
NameError - undefined local variable or method `name' for #<#<Class:0x007fef775a4da8>:0x007fef775b5b08>:
   () usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/datasource-bd75d8f581a6/lib/datasource/base.rb:149:in `fail_missing_attributes'
   () usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/datasource-bd75d8f581a6/lib/datasource/base.rb:138:in `select'
   () usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/datasource-bd75d8f581a6/lib/datasource/adapters/active_record.rb:30:in `get_datasource'
   () usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/datasource-bd75d8f581a6/lib/datasource/adapters/active_record.rb:38:in `exec_queries'
  activerecord (4.1.8) lib/active_record/relation.rb:493:in `load'
  activerecord (4.1.8) lib/active_record/relation.rb:238:in `to_a'
   () usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/datasource-bd75d8f581a6/lib/datasource/consumer_adapters/active_model_serializers.rb:15:in `initialize_with_datasource'
   () usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/bundler/gems/datasource-bd75d8f581a6/lib/datasource/consumer_adapters/active_model_serializers.rb:74:in `initialize'
  active_model_serializers (0.9.2) lib/action_controller/serialization.rb:76:in `build_json_serializer'
```

Look's like `fail_missing_attributes` was invoked in simple mode, but it shouldn't.

Maybe?

``` ruby
# https://github.com/mrbrdo/datasource/blob/master/lib/datasource/base.rb 138 line
fail_missing_attributes(missing_attributes) if missing_attributes.present? && Datasource.config.simple_mode
```

**Comment by mrbrdo** [comment]
there was a bug inside fail_missing_attributes. it still needs to be called, it means that you are trying to select an attribute datasource doesn't know about (and it should know about at least all the database columns, so it seems like you are selecting something else).
can you try with master, you should get a better error message now, and let me know.

thanks!

**Comment by mrbrdo** [comment]
actually, you are right, it shouldn't be called in simple mode :) should be fixed in master.

**Comment by mrbrdo** [comment]
let me know if that worked for you

**Comment by kirillplatonov** [comment]
Sorry for so late. Looks okay. No exceptions anymore.

**Comment by mrbrdo** [comment]
awesome, thanks for your help. hit me up if you have any other ideas or issues!
